[package]
name = "uplink"
version = "0.1.0"
authors = ["raviteja <mail@raviteja.tech>"]
edition = "2018"

[dependencies]
futures = "0.1"
tokio-current-thread = "0.1"
tokio-codec = "0.1"
tokio-udp = "0.1"
crossbeam-channel = "0.3"
maplit = "1"
derive_more = "0.13"