[package]
name = "uplink"
version = "0.1.0"
authors = ["tekjar <kraviteza@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam-channel = "0.3"
serde = {version = "1", features = ["derive"]}
serde_json = "1.0"
derive_more = "0.15"
structopt = "0.3"
toml = "0.5"
rumqtt = "0.31"
pretty_env_logger = "0.3"
rand = "0.7"
log = "0.4"
socketcan = "1"
hex = "0.4"