[package]
name = "uplink"
version = "0.1.0"
authors = ["tekjar <raviteja@bytebeam.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
tcpjson = []
simulator = []

default = ["tcpjson", "simulator"]

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
derive_more = { version = "0.99", features = ["from"] }
# rumq-client = { path = "../rumq/rumq-client" } 
rumq-client = { version = "0.1.0-alpha.5" }
log = "0.4"
tokio = { version = "0.2", features = ["full"] }
tokio-util = { version = "0.2", features = ["codec"] }
futures-util = "0.3"
structopt = "0.3"
rand = "0.7"
toml = "0.5"
pretty_env_logger = "0.4"