[package]
name = "uplink"
version = "1.1.0"
authors = ["tekjar <raviteja@bytebeam.io>"]
edition = "2018"

[dependencies]
disk = { path = "../disk" }
tokio = { version = "1", features = ["full"] }
tokio-util = { version = "0.6", features = ["codec"] }
tokio-stream = "0.1"
tokio-compat-02 = "0.2.0"
async-channel = "1.5"
rumqttc = "0.7"
# rumqttc = { path = "../../rumqtt/rumqttc" }
bytes = "1"
serde = { version = "1", features = ["derive"] }
thiserror = "1"
anyhow = "1"
serde_json = "1.0"
structopt = "0.3"
rand = "0.7"
toml = "0.5"
log = "0.4"
simplelog = "0.9"
tunshell-client = { git = "https://github.com/TimeToogo/tunshell.git" }
