[package]
name = "uplink"
version = "0.1.0"
authors = ["tekjar <raviteja@bytebeam.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
bridge = []

default = ["bridge"]

[dependencies]
persistentstream = { path = "../persistentstream", version = "0.1" }
tokio = { version = "1", features = ["full"] }
tokio-util = { version = "0.6", features = ["codec"] }
tokio-stream = "0.1"
rumqttc = "0.4"
serde = { version = "1", features = ["derive"] }
thiserror = "1"
anyhow = "1"
serde_json = "1.0"
structopt = "0.3"
rand = "0.7"
toml = "0.5"
log = "0.4"
pretty_env_logger = "0.4"
