[package]
name = "uplink"
version = "0.1.0"
authors = ["tekjar <raviteja@bytebeam.io>"]
edition = "2018"

[dependencies]
disk = { path = "../disk" }
tokio = { version = "1", features = ["full"] }
tokio-util = { version = "0.6", features = ["codec"] }
tokio-stream = "0.1"
rumqttc = { path = "../../rumqtt/rumqttc" }
async-channel = "1.5"
# rumqttc = "0.4"
bytes = "1"
serde = { version = "1", features = ["derive"] }
thiserror = "1"
anyhow = "1"
serde_json = "1.0"
structopt = "0.3"
rand = "0.7"
toml = "0.5"
log = "0.4"
pretty_env_logger = "0.4"
